### ISSUE TITLE
Use with Electron

### ISSUE THREAD

**Issue by Spiralis** [jinjor/elm-time-travel#13]
Since the official debugger has some issues this might be a good replacement for it. The official debugger in Electron has two issues:
1. The Import/Export "tab" must have its css `.elm-overlay` `z-index` bumped (minor problem though)
2. When clicking to open it fails to open in the new pop-up window that it generates. It might be possible to fix this, but I am not sure how. 

Instead I was thinking about trying this instead. I will keep you posted on the results of that.

FYI: The application I have is based on the [elm electron starter](https://github.com/dillonkearns/elm-electron-starter).

**Comment by ream88** [comment]
@Spiralis any update on this? I've encountered the same problems as described above 😞

**Comment by Spiralis** [comment]
Hm. Yes, We "fixed" it. We continued to add our own css for the `.elm-overlay`:
```
.elm-overlay {
  z-index: 1000;
}
```
But, not for the production version (although it would probably just be dead code in prod anyway).

For the debugger window to work. I tried different things. I **think** what we did was to add a setting , `webPreferences: {nativeWindowOpen: true}`, used like this:
```
  mainWindow = new BrowserWindow({ 
    width: windowWidth,
    height: windowHeight,
    webPreferences: {
      nativeWindowOpen: true
    } 
  })
```

**Comment by ream88** [comment]
Yep worked for me as well :)

**Comment by Derryrover** [comment]
Yes answer of Spiralis with webPreferences works. Thanks so much!
